#!/usr/bin/env bash

# https://github.com/ryanoasis/nerd-fonts/releases/latest
mkdir -p "$HOME/.local/share/fonts"
pushd "$HOME/.local/share/fonts/" && \
rm -rf ./* && \
curl -L "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.5.0/JetBrainsMono.tar.xz" | \
tar -xJf - && fc-cache -fv && \
popd

sudo pacman -S --needed --noconfirm nautilus fd ripgrep starship zoxide neovim wl-clipboard copyq git github-cli firefox lazygit man-db man-pages
sudo pacman -S --needed --noconfirm grim slurp satty
sudo pacman -S --needed --noconfirm noto-fonts noto-fonts-emoji noto-fonts-cjk noto-fonts-extra ttf-jetbrains-mono-nerd
paru -S --needed --noconfirm blesh-git
sudo man-db

sudo mkdir -p /etc/systemd/system/getty@tty1.service.d
sudo tee /etc/systemd/system/getty@tty1.service.d/override.conf > /dev/null << 'EOF'
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin iqrar --noclear %I $TERM
EOF
sudo systemctl daemon-reload
sudo systemctl restart getty@tty1
sudo reboot

# git clone <repo> ~/dotfiles
DOTFILES="$HOME/dotfiles"
shopt -s dotglob
for file in "$DOTFILES"/*; do
    ln -sfn "$file" "$HOME/$(basename "$file")"
done good? if $DOT/home/iqrar/.bashrc  mirrrors  HOME

BACKUP_DIR="$HOME/bak"

for file in "$DOTFILES"/*; do
    name="$(basename "$file")"
    [[ "$name" == ".git" ]] && continue
    target="$HOME/$name"
    if [[ -e "$target" && ! -L "$target" ]]; then
        mkdir -p "$BACKUP_DIR"
        mv "$target" "$BACKUP_DIR/$name.bak"
    fi
    ln -sfn "$file" "$target"
done

# ========================

mkdir -p ~/.src

git -C ~/.src clone --filter=blob:none --no-checkout https://github.com/prisma/web.git prisma
git -C ~/.src/prisma sparse-checkout set --no-cone \
  'apps/docs/content/docs/**/*.mdx' \
  '!apps/docs/content/docs/**/v6/**'
git -C ~/.src/prisma checkout

git -C ~/.src clone --filter=blob:none --no-checkout https://github.com/better-auth/better-auth.git better-auth
git -C ~/.src/better-auth sparse-checkout set --no-cone \
  'docs/content/docs/**/*.mdx'
git -C ~/.src/better-auth checkout

git -C ~/.src clone --filter=blob:none --no-checkout https://github.com/vercel/next.js.git next.js
git -C ~/.src/next.js sparse-checkout set --no-cone \
  'docs/01-app'
git -C ~/.src/next.js checkout

git -C ~/.src clone --filter=blob:none --no-checkout https://github.com/nodejs/node.git node
git -C ~/.src/node sparse-checkout set --no-cone \
  'doc/api'
git -C ~/.src/node checkout

git -C ~/.src clone --filter=blob:none --no-checkout https://github.com/mdn/content.git mdn
git -C ~/.src/mdn sparse-checkout set --no-cone \
  'files/en-us/web/api' \
  'files/en-us/web/http' \
  'files/en-us/web/javascript'
git -C ~/.src/mdn checkout

git -C ~/.src clone --filter=blob:none --no-checkout https://github.com/reactjs/react.dev.git react
git -C ~/.src/react sparse-checkout set --no-cone \
  'src/content/reference'
git -C ~/.src/react checkout

git -C ~/.src clone --filter=blob:none --no-checkout https://github.com/typescript-cheatsheets/react.git typescript-cheatsheets-react
git -C ~/.src/typescript-cheatsheets-react sparse-checkout set --no-cone \
  'docs'
git -C ~/.src/typescript-cheatsheets-react checkout
rm ~/.src/react/src/content/reference/_basic
rm ~/.src/react/src/content/reference/_api
ln -s ~/.src/typescript-cheatsheets-react/docs/basic/getting-started/ ~/.src/react/src/content/reference/_basic
ln -s ~/.src/typescript-cheatsheets-react/docs/reference/ ~/.src/react/src/content/reference/_api
