include kitty.conf
shell bash -c '/usr/bin/tmux attach 2>/dev/null || tmux new-session'

map shift+enter send_text all \x1b[13;2u
# Shift+Alt+Ctrl+Home
map alt+enter send_text all \x1b[1;8H
map ctrl+backspace send_text all \x1b[127;5u
# Shift+Alt+Ctrl+Left
map ctrl+enter send_text all \x1b[1;8D
# Shift+Alt+Ctrl+Right
map ctrl+shift+g send_text all \x1b[1;8C
# Shift+Alt+Ctrl+Down
map ctrl+shift+i send_text all \x1b[1;8B
# Shift+Alt+Ctrl+Up
map ctrl+shift+x send_text all \x1b[1;8A
# Shift+Alt+Ctrl+PageDown
map ctrl+comma send_text all \x1b[6;8~
# Shift+Alt+Ctrl+D
map alt+escape send_text all \x1b[100;8u

mouse_map left click grabbed,ungrabbed mouse_handle_click selection link prompt
mouse_map middle press grabbed,ungrabbed mouse_selection rectangle

# some special keys i.e. <A-"> wont work for tmux
map alt+1 send_key ctrl+g 1
map alt+2 send_key ctrl+g 2
map alt+3 send_key ctrl+g 3
map alt+4 send_key ctrl+g 4
map alt+5 send_key ctrl+g 5
map alt+6 send_key ctrl+g 6
map alt+7 send_key ctrl+g 7
map alt+8 send_key ctrl+g 8
map alt+9 kitten ~/dotfiles/.config/kitty/last_win.py
map ctrl+shift+e kitten ~/dotfiles/.config/kitty/move_tab_to.py 1
map ctrl+shift+j kitten ~/dotfiles/.config/kitty/move_tab_to.py 2
map ctrl+shift+k kitten ~/dotfiles/.config/kitty/move_tab_to.py 3
map ctrl+shift+l kitten ~/dotfiles/.config/kitty/move_tab_to.py 4
map alt+shift+e kitten ~/dotfiles/.config/kitty/move_tab_to.py 5
map alt+shift+j kitten ~/dotfiles/.config/kitty/move_tab_to.py 6
map alt+shift+k kitten ~/dotfiles/.config/kitty/move_tab_to.py 7
map alt+shift+l kitten ~/dotfiles/.config/kitty/move_tab_to.py 8
map ctrl+shift+enter kitten ~/dotfiles/.config/kitty/move_tab_to.py

action_alias myhints kitten hints --alphabet efhadlscvmnrtwpoijgb,qxuyk-{}[]_=()<>+.?~#*^&`@!\"$\'%EFHADLSCVMNRTWPOIJGBQXUYK

map ctrl+g>alt+&>a myhints --type=word --program=default
map ctrl+g>alt+&>b myhints --type=word --program=-
map ctrl+g>alt+&>c myhints --type=word --program=@
